ALTER TABLE notifications ADD COLUMN IF NOT EXISTS priority VARCHAR(20) DEFAULT 'medium';
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS action_label VARCHAR(50);
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS action_link VARCHAR(255);
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS created_by VARCHAR(255) DEFAULT 'system';
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS read_at TIMESTAMP WITH TIME ZONE;
