import { DataSource } from './dto/report.dto';

export const REPORT_DATA_SOURCES: DataSource[] = [
  {
    table: 'staff',
    label: 'Staff Members',
    fields: [
      { field: 'staff_number', type: 'string', label: 'Staff Number', isSearchable: true, isFilterable: true, isAggregatable: false },
      { field: 'first_name', type: 'string', label: 'First Name', isSearchable: true, isFilterable: true, isAggregatable: false },
      { field: 'last_name', type: 'string', label: 'Last Name', isSearchable: true, isFilterable: true, isAggregatable: false },
      { field: 'email', type: 'string', label: 'Email', isSearchable: true, isFilterable: true, isAggregatable: false },
      { field: 'designation', type: 'string', label: 'Designation', isSearchable: false, isFilterable: true, isAggregatable: false },
      { field: 'employment_type', type: 'string', label: 'Employment Type', isSearchable: false, isFilterable: true, isAggregatable: false },
      { field: 'current_basic_salary', type: 'number', label: 'Basic Salary', isSearchable: false, isFilterable: true, isAggregatable: true },
      { field: 'employment_date', type: 'date', label: 'Employment Date', isSearchable: false, isFilterable: true, isAggregatable: false },
      { field: 'status', type: 'string', label: 'Status', isSearchable: false, isFilterable: true, isAggregatable: false },
    ],
    relationships: [{ table: 'departments', field: 'department_id', foreignKey: 'id' }],
  },
  {
    table: 'departments',
    label: 'Departments',
    fields: [
      { field: 'code', type: 'string', label: 'Code', isSearchable: true, isFilterable: true, isAggregatable: false },
      { field: 'name', type: 'string', label: 'Name', isSearchable: true, isFilterable: true, isAggregatable: false },
      { field: 'description', type: 'string', label: 'Description', isSearchable: true, isFilterable: false, isAggregatable: false },
    ],
    relationships: [],
  },
  {
    table: 'payroll_batches',
    label: 'Payroll Batches',
    fields: [
      { field: 'batch_number', type: 'string', label: 'Batch Number', isSearchable: true, isFilterable: true, isAggregatable: false },
      { field: 'payroll_month', type: 'string', label: 'Payroll Month', isSearchable: false, isFilterable: true, isAggregatable: false },
      { field: 'status', type: 'string', label: 'Status', isSearchable: false, isFilterable: true, isAggregatable: false },
      { field: 'total_staff', type: 'number', label: 'Total Staff', isSearchable: false, isFilterable: true, isAggregatable: true },
      { field: 'total_gross', type: 'number', label: 'Total Gross Pay', isSearchable: false, isFilterable: true, isAggregatable: true },
      { field: 'total_deductions', type: 'number', label: 'Total Deductions', isSearchable: false, isFilterable: true, isAggregatable: true },
      { field: 'total_net', type: 'number', label: 'Total Net Pay', isSearchable: false, isFilterable: true, isAggregatable: true },
    ],
    relationships: [],
  },
  {
    table: 'payroll_lines',
    label: 'Payroll Details',
    fields: [
      { field: 'payroll_batch_id', type: 'string', label: 'Payroll Batch ID', isSearchable: false, isFilterable: true, isAggregatable: false },
      { field: 'staff_id', type: 'string', label: 'Staff ID', isSearchable: false, isFilterable: true, isAggregatable: false },
      { field: 'bank_name', type: 'string', label: 'Bank Name', isSearchable: true, isFilterable: true, isAggregatable: false },
      { field: 'account_number', type: 'string', label: 'Account Number', isSearchable: true, isFilterable: true, isAggregatable: false },
      { field: 'grade_level', type: 'string', label: 'Grade Level', isSearchable: false, isFilterable: true, isAggregatable: false },
      { field: 'step', type: 'number', label: 'Step', isSearchable: false, isFilterable: true, isAggregatable: false },
      { field: 'basic_salary', type: 'number', label: 'Basic Salary', isSearchable: false, isFilterable: true, isAggregatable: true },
      { field: 'gross_pay', type: 'number', label: 'Gross Pay', isSearchable: false, isFilterable: true, isAggregatable: true },
      { field: 'total_deductions', type: 'number', label: 'Total Deductions', isSearchable: false, isFilterable: true, isAggregatable: true },
      { field: 'net_pay', type: 'number', label: 'Net Pay', isSearchable: false, isFilterable: true, isAggregatable: true },
    ],
    relationships: [
      { table: 'payroll_batches', field: 'payroll_batch_id', foreignKey: 'id' },
      { table: 'staff', field: 'staff_id', foreignKey: 'id' },
    ],
  },
  {
    table: 'loan_applications',
    label: 'Loan Applications',
    fields: [
      { field: 'application_number', type: 'string', label: 'Application Number', isSearchable: true, isFilterable: true, isAggregatable: false },
      { field: 'amount_requested', type: 'number', label: 'Requested Amount', isSearchable: false, isFilterable: true, isAggregatable: true },
      { field: 'tenure_months', type: 'number', label: 'Tenure (Months)', isSearchable: false, isFilterable: true, isAggregatable: true },
      { field: 'status', type: 'string', label: 'Status', isSearchable: false, isFilterable: true, isAggregatable: false },
    ],
    relationships: [
      { table: 'staff', field: 'staff_id', foreignKey: 'id' },
      { table: 'loan_types', field: 'loan_type_id', foreignKey: 'id' },
    ],
  },
  {
    table: 'leave_requests',
    label: 'Leave Requests',
    fields: [
      { field: 'request_number', type: 'string', label: 'Request Number', isSearchable: true, isFilterable: true, isAggregatable: false },
      { field: 'start_date', type: 'date', label: 'Start Date', isSearchable: false, isFilterable: true, isAggregatable: false },
      { field: 'end_date', type: 'date', label: 'End Date', isSearchable: false, isFilterable: true, isAggregatable: false },
      { field: 'number_of_days', type: 'number', label: 'Number of Days', isSearchable: false, isFilterable: true, isAggregatable: true },
      { field: 'status', type: 'string', label: 'Status', isSearchable: false, isFilterable: true, isAggregatable: false },
    ],
    relationships: [
      { table: 'staff', field: 'staff_id', foreignKey: 'id' },
      { table: 'leave_types', field: 'leave_type_id', foreignKey: 'id' },
    ],
  },
  {
    table: 'cooperatives',
    label: 'Cooperatives',
    fields: [
      { field: 'code', type: 'string', label: 'Code', isSearchable: true, isFilterable: true, isAggregatable: false },
      { field: 'name', type: 'string', label: 'Name', isSearchable: true, isFilterable: true, isAggregatable: false },
      { field: 'type', type: 'string', label: 'Type', isSearchable: false, isFilterable: true, isAggregatable: false },
      { field: 'monthly_contribution', type: 'number', label: 'Monthly Contribution', isSearchable: false, isFilterable: true, isAggregatable: true },
    ],
    relationships: [],
  },
  {
    table: 'cooperative_members',
    label: 'Cooperative Members',
    fields: [
      { field: 'member_number', type: 'string', label: 'Member Number', isSearchable: true, isFilterable: true, isAggregatable: false },
      { field: 'cooperative_id', type: 'string', label: 'Cooperative ID', isSearchable: false, isFilterable: true, isAggregatable: false },
      { field: 'staff_id', type: 'string', label: 'Staff ID', isSearchable: false, isFilterable: true, isAggregatable: false },
      { field: 'monthly_contribution', type: 'number', label: 'Monthly Contribution', isSearchable: false, isFilterable: true, isAggregatable: true },
      { field: 'total_contributions', type: 'number', label: 'Total Contributions', isSearchable: false, isFilterable: true, isAggregatable: true },
      { field: 'status', type: 'string', label: 'Status', isSearchable: false, isFilterable: true, isAggregatable: false },
    ],
    relationships: [],
  },
  {
    table: 'cooperative_contributions',
    label: 'Cooperative Contributions',
    fields: [
      { field: 'cooperative_id', type: 'string', label: 'Cooperative ID', isSearchable: false, isFilterable: true, isAggregatable: false },
      { field: 'member_id', type: 'string', label: 'Member ID', isSearchable: false, isFilterable: true, isAggregatable: false },
      { field: 'amount', type: 'number', label: 'Amount', isSearchable: false, isFilterable: true, isAggregatable: true },
      { field: 'contribution_month', type: 'string', label: 'Contribution Month', isSearchable: false, isFilterable: true, isAggregatable: false },
      { field: 'payroll_batch_id', type: 'string', label: 'Payroll Batch ID', isSearchable: false, isFilterable: true, isAggregatable: false },
    ],
    relationships: [],
  },
  {
    table: 'loan_types',
    label: 'Loan Types',
    fields: [
      { field: 'code', type: 'string', label: 'Code', isSearchable: true, isFilterable: true, isAggregatable: false },
      { field: 'name', type: 'string', label: 'Name', isSearchable: true, isFilterable: true, isAggregatable: false },
      { field: 'interest_rate', type: 'number', label: 'Interest Rate', isSearchable: false, isFilterable: true, isAggregatable: true },
      { field: 'max_amount', type: 'number', label: 'Max Amount', isSearchable: false, isFilterable: true, isAggregatable: true },
      { field: 'max_tenure_months', type: 'number', label: 'Max Tenure (Months)', isSearchable: false, isFilterable: true, isAggregatable: true },
      { field: 'cooperative_id', type: 'string', label: 'Cooperative ID', isSearchable: false, isFilterable: true, isAggregatable: false },
      { field: 'status', type: 'string', label: 'Status', isSearchable: false, isFilterable: true, isAggregatable: false },
    ],
    relationships: [],
  },
  {
    table: 'loan_disbursements',
    label: 'Loan Disbursements',
    fields: [
      { field: 'disbursement_number', type: 'string', label: 'Disbursement Number', isSearchable: true, isFilterable: true, isAggregatable: false },
      { field: 'loan_application_id', type: 'string', label: 'Loan Application ID', isSearchable: false, isFilterable: true, isAggregatable: false },
      { field: 'staff_id', type: 'string', label: 'Staff ID', isSearchable: false, isFilterable: true, isAggregatable: false },
      { field: 'amount_disbursed', type: 'number', label: 'Amount Disbursed', isSearchable: false, isFilterable: true, isAggregatable: true },
      { field: 'disbursement_date', type: 'date', label: 'Disbursement Date', isSearchable: false, isFilterable: true, isAggregatable: false },
      { field: 'start_month', type: 'string', label: 'Start Month', isSearchable: false, isFilterable: true, isAggregatable: false },
      { field: 'end_month', type: 'string', label: 'End Month', isSearchable: false, isFilterable: true, isAggregatable: false },
      { field: 'monthly_deduction', type: 'number', label: 'Monthly Deduction', isSearchable: false, isFilterable: true, isAggregatable: true },
      { field: 'balance', type: 'number', label: 'Balance', isSearchable: false, isFilterable: true, isAggregatable: true },
      { field: 'status', type: 'string', label: 'Status', isSearchable: false, isFilterable: true, isAggregatable: false },
    ],
    relationships: [],
  },
  {
    table: 'loan_repayments',
    label: 'Loan Repayments',
    fields: [
      { field: 'disbursement_id', type: 'string', label: 'Disbursement ID', isSearchable: false, isFilterable: true, isAggregatable: false },
      { field: 'staff_id', type: 'string', label: 'Staff ID', isSearchable: false, isFilterable: true, isAggregatable: false },
      { field: 'amount', type: 'number', label: 'Amount', isSearchable: false, isFilterable: true, isAggregatable: true },
      { field: 'repayment_date', type: 'date', label: 'Repayment Date', isSearchable: false, isFilterable: true, isAggregatable: false },
      { field: 'month', type: 'string', label: 'Repayment Month', isSearchable: false, isFilterable: true, isAggregatable: false },
      { field: 'payment_method', type: 'string', label: 'Payment Method', isSearchable: false, isFilterable: true, isAggregatable: false },
      { field: 'reference_number', type: 'string', label: 'Reference Number', isSearchable: true, isFilterable: true, isAggregatable: false },
    ],
    relationships: [],
  },
  {
    table: 'leave_types',
    label: 'Leave Types',
    fields: [
      { field: 'name', type: 'string', label: 'Name', isSearchable: true, isFilterable: true, isAggregatable: false },
      { field: 'annual_days', type: 'number', label: 'Annual Days', isSearchable: false, isFilterable: true, isAggregatable: true },
      { field: 'is_paid', type: 'boolean', label: 'Is Paid', isSearchable: false, isFilterable: true, isAggregatable: false },
      { field: 'carries_forward', type: 'boolean', label: 'Carries Forward', isSearchable: false, isFilterable: true, isAggregatable: false },
      { field: 'status', type: 'string', label: 'Status', isSearchable: false, isFilterable: true, isAggregatable: false },
    ],
    relationships: [],
  },
  {
    table: 'users',
    label: 'Users',
    fields: [
      { field: 'email', type: 'string', label: 'Email', isSearchable: true, isFilterable: true, isAggregatable: false },
      { field: 'full_name', type: 'string', label: 'Full Name', isSearchable: true, isFilterable: true, isAggregatable: false },
      { field: 'role', type: 'string', label: 'Role', isSearchable: false, isFilterable: true, isAggregatable: false },
      { field: 'staff_id', type: 'string', label: 'Staff ID', isSearchable: false, isFilterable: true, isAggregatable: false },
      { field: 'status', type: 'string', label: 'Status', isSearchable: false, isFilterable: true, isAggregatable: false },
    ],
    relationships: [],
  },
  {
    table: 'audit_trail',
    label: 'Audit Trail',
    fields: [
      { field: 'action', type: 'string', label: 'Action', isSearchable: false, isFilterable: true, isAggregatable: false },
      { field: 'entity', type: 'string', label: 'Entity', isSearchable: true, isFilterable: true, isAggregatable: false },
      { field: 'description', type: 'string', label: 'Description', isSearchable: true, isFilterable: false, isAggregatable: false },
      { field: 'created_at', type: 'date', label: 'Date/Time', isSearchable: false, isFilterable: true, isAggregatable: false },
    ],
    relationships: [{ table: 'users', field: 'user_id', foreignKey: 'id' }],
  },
];
